services:
  
  tsapp_backend:
    build: .
    container_name: tsapp_backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build:  .
    command:  celery -A config worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - tsapp_backend
      - redis

  redis:
    image: "redis:alpine"