name: StatusApp-backend-CICD
on: 
    push:
      branches: [ gha-prod ]
      
jobs:
    docker:
      name: Docker build and Push
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_STATUS_APPS_ACCESS_KEY}}
            aws-secret-access-key: ${{secrets.AWS_STATUS_APPS_SECRET_KEY}}
            aws-region: us-east-2
        - name: Build Docker
          run: |
            pwd
            ls -lrt

      